import { NextRequest, NextResponse } from 'next/server';
import { 
  getSheetsData, 
  appendSheetsData, 
  updateSheetRow, 
  deleteSheetRow 
} from '@/lib/google-sheets';
import { CONFIG } from '@/lib/config';

const SHEET_ID = CONFIG.SALES.SHEET_ID;
const SHEET_NAME = CONFIG.SALES.SHEET_NAME;

// Headers:
// A: Id
// B: Timestamp
// C: Name
// D: Address
// E: Contact No.
// F: Salesman
// G: City Type
// H: Reference by
// I: Generated by
// J: Lead Type
// K: Type of Client
// L: Name Of Builder (11)
// M: Planned_1 (12)
// N: Actual_1 (13)
// O: Status_1 (14)
// P: Planned_2 (15)
// Q: Actual_2 (16)
// R: Status_2 (17)
// S: Next_Follow_Up_Date_2 (18)
// T: Remarks_2 (19)
// U: Planned_3 (20)
// V: Actual_3 (21)
// W: Status_3 (22)
// X: Next_Follow_Up_Date_3 (23)
// Y: Remark_3 (24)
// Z: Planned_4 (25)
// AA: Actual_4 (26)
// AB: Status_4 (27)
// AC: Meeting_Mode_4 (28)
// AD: Next_Follow_Up_Date_4 (29)
// AE: Remark_4 (30)
// AF: Planned_5 (31)
// AG: Actual_5 (32)
// AH: Status_5 (33)
// AI: Next_Follow_Up_Date_5 (34)
// AJ: Remark_5 (35)
// AK: Planned_6 (36)
// AL: Actual_6 (37)
// AM: Status_6 (38)
// AN: Lost_Remark (39)

export async function GET() {
  try {
    const data = await getSheetsData(SHEET_ID, `${SHEET_NAME}!A2:AN1000`);

    if (!data || data.length === 0) return NextResponse.json([]);

    const sales = data.map((row: string[], index: number) => {
      return {
        rowIndex: index + 2,
        id: row[0] || '',
        timestamp: row[1] || '',
        name: row[2] || '',
        address: row[3] || '',
        contactNo: row[4] || '',
        salesman: row[5] || '',
        cityType: row[6] || '',
        referenceBy: row[7] || '',
        generatedBy: row[8] || '',
        leadType: row[9] || '',
        typeOfClient: row[10] || '',
        nameOfBuilder: row[11] || '',
        planned_1: row[12] || '',
        actual_1: row[13] || '',
        status_1: row[14] || '',
        planned_2: row[15] || '',
        actual_2: row[16] || '',
        status_2: row[17] || '',
        next_follow_up_date_2: row[18] || '',
        remarks_2: row[19] || '',
        planned_3: row[20] || '',
        actual_3: row[21] || '',
        status_3: row[22] || '',
        next_follow_up_date_3: row[23] || '',
        remark_3: row[24] || '',
        planned_4: row[25] || '',
        actual_4: row[26] || '',
        status_4: row[27] || '',
        meeting_mode_4: row[28] || '',
        next_follow_up_date_4: row[29] || '',
        remark_4: row[30] || '',
        planned_5: row[31] || '',
        actual_5: row[32] || '',
        status_5: row[33] || '',
        next_follow_up_date_5: row[34] || '',
        remark_5: row[35] || '',
        planned_6: row[36] || '',
        actual_6: row[37] || '',
        status_6: row[38] || '',
        lost_remark: row[39] || '',
      };
    });

    return NextResponse.json(sales);
  } catch (error: unknown) {
    const err = error as Error;
    console.error('API Error (GET Sales):', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData();
    const name = formData.get('name') as string;
    const address = formData.get('address') as string;
    const contactNo = formData.get('contactNo') as string;
    const salesman = formData.get('salesman') as string;
    const cityType = formData.get('cityType') as string;
    const referenceBy = formData.get('referenceBy') as string;
    const generatedBy = formData.get('generatedBy') as string;
    const leadType = formData.get('leadType') as string;
    const typeOfClient = formData.get('typeOfClient') as string;
    const nameOfBuilder = formData.get('nameOfBuilder') as string;

    if (!name) {
      return NextResponse.json({ error: 'Name is required.' }, { status: 400 });
    }

    // Get current maximum ID to generate the next one (Lead-1, Lead-2, etc.)
    let nextIdNumber = 1;
    try {
      const existingData = await getSheetsData(SHEET_ID, `${SHEET_NAME}!A2:A1000`);
      if (existingData && existingData.length > 0) {
        let maxNumber = 0;
        existingData.forEach((row: string[]) => {
          if (row[0] && row[0].startsWith('Lead-')) {
            const numStr = row[0].replace('Lead-', '');
            const num = parseInt(numStr, 10);
            if (!isNaN(num) && num > maxNumber) {
              maxNumber = num;
            }
          }
        });
        nextIdNumber = maxNumber + 1;
      }
    } catch (e) {
      console.log('Error fetching existing IDs, starting at 1', e);
    }
    
    const id = `Lead-${nextIdNumber}`;
    const timestamp = new Date().toISOString();

    const plannedDate = new Date();
    plannedDate.setDate(plannedDate.getDate() + 1);
    if (plannedDate.getDay() === 0) { // Sunday
      plannedDate.setDate(plannedDate.getDate() + 1);
    }

    const newRow = [
      id,
      timestamp,
      name,
      address || '',
      contactNo || '',
      salesman || '',
      cityType || '',
      referenceBy || '',
      generatedBy || '',
      leadType || '',
      typeOfClient || '',
      nameOfBuilder || '',
      plannedDate.toISOString(),
      ...Array(27).fill('') // Padding columns N (13) to AN (39)
    ];

    await appendSheetsData(SHEET_ID, `${SHEET_NAME}!A2`, [newRow]);

    return NextResponse.json({ success: true, id });
  } catch (error: unknown) {
    const err = error as Error;
    console.error('API Error (POST Sales):', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function PUT(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const rowIndexStr = searchParams.get('rowIndex');

    if (!rowIndexStr) return NextResponse.json({ error: 'Missing Row Index' }, { status: 400 });
    const rowIndex = parseInt(rowIndexStr);

    const formData = await request.formData();
    const id = formData.get('id') as string;
    const timestamp = formData.get('timestamp') as string;
    const name = formData.get('name') as string;
    const address = formData.get('address') as string;
    const contactNo = formData.get('contactNo') as string;
    const salesman = formData.get('salesman') as string;
    const cityType = formData.get('cityType') as string;
    const referenceBy = formData.get('referenceBy') as string;
    const generatedBy = formData.get('generatedBy') as string;
    const leadType = formData.get('leadType') as string;
    const typeOfClient = formData.get('typeOfClient') as string;
    const nameOfBuilder = formData.get('nameOfBuilder') as string;

    if (!id || !name) {
      return NextResponse.json({ error: 'Missing required parameters' }, { status: 400 });
    }

    const updatedRow = [
      id,
      timestamp || new Date().toISOString(),
      name,
      address || '',
      contactNo || '',
      salesman || '',
      cityType || '',
      referenceBy || '',
      generatedBy || '',
      leadType || '',
      typeOfClient || '',
      nameOfBuilder || '',
      formData.get('planned_1') as string || '',
      formData.get('actual_1') as string || '',
      formData.get('status_1') as string || '',
      formData.get('planned_2') as string || '',
      formData.get('actual_2') as string || '',
      formData.get('status_2') as string || '',
      formData.get('next_follow_up_date_2') as string || '',
      formData.get('remarks_2') as string || '',
      formData.get('planned_3') as string || '',
      formData.get('actual_3') as string || '',
      formData.get('status_3') as string || '',
      formData.get('next_follow_up_date_3') as string || '',
      formData.get('remark_3') as string || '',
      formData.get('planned_4') as string || '',
      formData.get('actual_4') as string || '',
      formData.get('status_4') as string || '',
      formData.get('meeting_mode_4') as string || '',
      formData.get('next_follow_up_date_4') as string || '',
      formData.get('remark_4') as string || '',
      formData.get('planned_5') as string || '',
      formData.get('actual_5') as string || '',
      formData.get('status_5') as string || '',
      formData.get('next_follow_up_date_5') as string || '',
      formData.get('remark_5') as string || '',
      formData.get('planned_6') as string || '',
      formData.get('actual_6') as string || '',
      formData.get('status_6') as string || '',
      formData.get('lost_remark') as string || ''
    ];

    await updateSheetRow(SHEET_ID, `${SHEET_NAME}!A${rowIndex}:AN${rowIndex}`, [updatedRow]);

    return NextResponse.json({ success: true });
  } catch (error: unknown) {
    const err = error as Error;
    console.error('API Error (PUT Sales):', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const rowIndexStr = searchParams.get('rowIndex');

    if (!rowIndexStr) return NextResponse.json({ error: 'Missing Row Index' }, { status: 400 });
    const rowIndex = parseInt(rowIndexStr);

    await deleteSheetRow(SHEET_ID, SHEET_NAME, rowIndex - 1);

    return NextResponse.json({ success: true });
  } catch (error: unknown) {
    const err = error as Error;
    console.error('API Error (DELETE Sales):', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
