import { NextRequest, NextResponse } from 'next/server';
import { 
  getSheetsData, 
  appendSheetsData, 
  updateSheetRow, 
  deleteSheetRow 
} from '@/lib/google-sheets';
import { CONFIG } from '@/lib/config';

const SHEET_ID = CONFIG.SALES.SHEET_ID;
const SHEET_NAME = CONFIG.SALES.SHEET_NAME;

// Headers:
// A: Id
// B: Timestamp
// C: Name
// D: Address
// E: Contact No.
// F: Salesman
// G: City Type
// H: Reference by
// I: Generated by
// J: Lead Type
// K: Type of Client
// L: Name Of Builder

export async function GET() {
  try {
    const data = await getSheetsData(SHEET_ID, `${SHEET_NAME}!A2:L1000`);

    if (!data || data.length === 0) return NextResponse.json([]);

    const sales = data.map((row: string[], index: number) => {
      return {
        rowIndex: index + 2,
        id: row[0] || '',
        timestamp: row[1] || '',
        name: row[2] || '',
        address: row[3] || '',
        contactNo: row[4] || '',
        salesman: row[5] || '',
        cityType: row[6] || '',
        referenceBy: row[7] || '',
        generatedBy: row[8] || '',
        leadType: row[9] || '',
        typeOfClient: row[10] || '',
        nameOfBuilder: row[11] || '',
      };
    });

    return NextResponse.json(sales);
  } catch (error: unknown) {
    const err = error as Error;
    console.error('API Error (GET Sales):', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData();
    const name = formData.get('name') as string;
    const address = formData.get('address') as string;
    const contactNo = formData.get('contactNo') as string;
    const salesman = formData.get('salesman') as string;
    const cityType = formData.get('cityType') as string;
    const referenceBy = formData.get('referenceBy') as string;
    const generatedBy = formData.get('generatedBy') as string;
    const leadType = formData.get('leadType') as string;
    const typeOfClient = formData.get('typeOfClient') as string;
    const nameOfBuilder = formData.get('nameOfBuilder') as string;

    if (!name) {
      return NextResponse.json({ error: 'Name is required.' }, { status: 400 });
    }

    // Get current maximum ID to generate the next one (Lead-1, Lead-2, etc.)
    let nextIdNumber = 1;
    try {
      const existingData = await getSheetsData(SHEET_ID, `${SHEET_NAME}!A2:A1000`);
      if (existingData && existingData.length > 0) {
        let maxNumber = 0;
        existingData.forEach((row: string[]) => {
          if (row[0] && row[0].startsWith('Lead-')) {
            const numStr = row[0].replace('Lead-', '');
            const num = parseInt(numStr, 10);
            if (!isNaN(num) && num > maxNumber) {
              maxNumber = num;
            }
          }
        });
        nextIdNumber = maxNumber + 1;
      }
    } catch (e) {
      console.log('Error fetching existing IDs, starting at 1', e);
    }
    
    const id = `Lead-${nextIdNumber}`;
    const timestamp = new Date().toISOString();

    const newRow = [
      id,
      timestamp,
      name,
      address || '',
      contactNo || '',
      salesman || '',
      cityType || '',
      referenceBy || '',
      generatedBy || '',
      leadType || '',
      typeOfClient || '',
      nameOfBuilder || ''
    ];

    await appendSheetsData(SHEET_ID, `${SHEET_NAME}!A2`, [newRow]);

    return NextResponse.json({ success: true, id });
  } catch (error: unknown) {
    const err = error as Error;
    console.error('API Error (POST Sales):', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function PUT(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const rowIndexStr = searchParams.get('rowIndex');

    if (!rowIndexStr) return NextResponse.json({ error: 'Missing Row Index' }, { status: 400 });
    const rowIndex = parseInt(rowIndexStr);

    const formData = await request.formData();
    const id = formData.get('id') as string;
    const timestamp = formData.get('timestamp') as string;
    const name = formData.get('name') as string;
    const address = formData.get('address') as string;
    const contactNo = formData.get('contactNo') as string;
    const salesman = formData.get('salesman') as string;
    const cityType = formData.get('cityType') as string;
    const referenceBy = formData.get('referenceBy') as string;
    const generatedBy = formData.get('generatedBy') as string;
    const leadType = formData.get('leadType') as string;
    const typeOfClient = formData.get('typeOfClient') as string;
    const nameOfBuilder = formData.get('nameOfBuilder') as string;

    if (!id || !name) {
      return NextResponse.json({ error: 'Missing required parameters' }, { status: 400 });
    }

    const updatedRow = [
      id,
      timestamp || new Date().toISOString(),
      name,
      address || '',
      contactNo || '',
      salesman || '',
      cityType || '',
      referenceBy || '',
      generatedBy || '',
      leadType || '',
      typeOfClient || '',
      nameOfBuilder || ''
    ];

    await updateSheetRow(SHEET_ID, `${SHEET_NAME}!A${rowIndex}:L${rowIndex}`, [updatedRow]);

    return NextResponse.json({ success: true });
  } catch (error: unknown) {
    const err = error as Error;
    console.error('API Error (PUT Sales):', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const rowIndexStr = searchParams.get('rowIndex');

    if (!rowIndexStr) return NextResponse.json({ error: 'Missing Row Index' }, { status: 400 });
    const rowIndex = parseInt(rowIndexStr);

    await deleteSheetRow(SHEET_ID, SHEET_NAME, rowIndex - 1);

    return NextResponse.json({ success: true });
  } catch (error: unknown) {
    const err = error as Error;
    console.error('API Error (DELETE Sales):', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
